// Type colors for Pokemon badges - same as PokemonCard
export const typeColors: { [key: string]: string } = {
  Normal: "bg-gray-400 text-white",
  Fire: "bg-red-500 text-white", 
  Water: "bg-blue-500 text-white",
  Electric: "bg-yellow-400 text-black",
  Grass: "bg-green-500 text-white",
  Ice: "bg-blue-200 text-black",
  Fighting: "bg-red-700 text-white",
  Poison: "bg-purple-500 text-white",
  Ground: "bg-yellow-600 text-white",
  Flying: "bg-indigo-400 text-white",
  Psychic: "bg-pink-500 text-white",
  Bug: "bg-green-400 text-white",
  Rock: "bg-yellow-800 text-white",
  Ghost: "bg-purple-700 text-white",
  Dragon: "bg-indigo-700 text-white",
  Dark: "bg-gray-800 text-white",
  Steel: "bg-gray-600 text-white",
  Fairy: "bg-pink-300 text-black",
};
